name: Deploy Laravel to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build and Deploy Laravel via SSH to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: SSH & Deploy to EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            sudo rm -rf /var/www/laravel_app
            cd /home/ubuntu

            echo "Pulling latest code..."
            git clone git@github.com:Hamza-Yousaf109/laravel_app.git
            sudo mv ~/laravel_app /var/www/
            cd /var/www/laravel_app

            echo "Installing PHP dependencies..."
            sudo composer install --no-interaction --prefer-dist --optimize-autoloader

            echo "Setting correct permissions..."
            sudo chown -R www-data:www-data .
            sudo chmod -R 755 .

            echo "Copying .env if not exists..."
            sudo cp .env.example .env || true

            echo "Generating Laravel application key..."
            sudo php artisan key:generate

            echo "Running migrations..."
            sudo php artisan migrate --force

            echo "Clearing and caching config..."
            sudo php artisan config:clear
            sudo php artisan config:cache
            sudo php artisan route:cache
            sudo php artisan view:cache

            echo "Restarting PHP-FPM..."
            sudo systemctl restart php8.2-fpm || sudo systemctl restart php8.1-fpm || true
