name: Deploy Laravel to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build and Deploy Laravel via SSH to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: SSH & Deploy to EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            cd /var/www/laravel_app

            echo "Pulling latest code..."
            git pull origin main

            echo "Installing PHP dependencies..."
            composer install --no-interaction --prefer-dist --optimize-autoloader

            echo "Setting correct permissions..."
            sudo chown -R www-data:www-data .
            sudo chmod -R 755 .

            echo "Copying .env if not exists..."
            cp .env.example .env || true

            echo "Generating Laravel application key..."
            php artisan key:generate

            echo "Running migrations..."
            php artisan migrate --force

            echo "Clearing and caching config..."
            php artisan config:clear
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache

            echo "Restarting PHP-FPM..."
            sudo systemctl restart php8.2-fpm || sudo systemctl restart php8.1-fpm || true
